from PyQt5.QtCore import QObject, QThread, pyqtSignal
import PyQt5.QtWidgets as qtw
import PyQt5.QtGui as qtg
import Midi_Input as mi
import replacR as rr
# import subprocess
import sys

class Worker(QObject):
    finished = pyqtSignal()

    def run(self):
        # Here we pass the update_progress (uncalled!)
        # function to the long_running_function:
        # executeMidiInput()
        mi.runMidi()
        self.finished.emit()

class MainWindow(qtw.QWidget):
    def __init__(self):
        super().__init__()
        self.setWindowTitle('Launchdeck')
        self.setFixedWidth(400)
        self.setFixedHeight(400)
        self.setStyleSheet("background-color: #1f1f1f;")
        # self.setStyleSheet("QPushButton {color: #bababa;}")
        self.setLayout(qtw.QVBoxLayout())
        self.topgrid()
        self.buttongrid()

        self.show()

    def topgrid(self):
        container2 = qtw.QWidget()
        container2.setLayout(qtw.QGridLayout())
        
        titleLP = qtw.QLabel('Launchdeck')
        comboBox = qtw.QComboBox(self)
        btn_start = qtw.QPushButton('Start', clicked = self.execute)

        container2.layout().addWidget(titleLP, 0, 0)
        container2.layout().addWidget(btn_start, 0, 4)

        comboBox.addItem("select function")
        comboBox.addItem("open file")
        comboBox.addItem("open chrome tab")
        comboBox.addItem("keyboard shortcut")
        container2.layout().addWidget(comboBox, 0, 1)
        comboBox.activated[str].connect(self.onActivated)
        
        self.layout().addWidget(container2)
        
    def buttongrid(self):
        container = qtw.QWidget()
        container.setLayout(qtw.QGridLayout())
        
        btn_11 = qtw.QPushButton(clicked = lambda: self.buttonselect("11"))
        btn_12 = qtw.QPushButton(clicked = lambda: self.buttonselect('12'))
        btn_13 = qtw.QPushButton(clicked = lambda: self.buttonselect('13'))
        btn_14 = qtw.QPushButton(clicked = lambda: self.buttonselect('14'))
        btn_15 = qtw.QPushButton(clicked = lambda: self.buttonselect('15'))
        btn_16 = qtw.QPushButton(clicked = lambda: self.buttonselect('16'))
        btn_17 = qtw.QPushButton(clicked = lambda: self.buttonselect('17'))
        btn_18 = qtw.QPushButton(clicked = lambda: self.buttonselect('18'))
        btn_19 = qtw.QPushButton(clicked = lambda: self.buttonselect('19'))
        btn_21 = qtw.QPushButton(clicked = lambda: self.buttonselect('21'))
        btn_22 = qtw.QPushButton(clicked = lambda: self.buttonselect('22'))
        btn_23 = qtw.QPushButton(clicked = lambda: self.buttonselect('23'))
        btn_24 = qtw.QPushButton(clicked = lambda: self.buttonselect('24'))
        btn_25 = qtw.QPushButton(clicked = lambda: self.buttonselect('25'))
        btn_26 = qtw.QPushButton(clicked = lambda: self.buttonselect('26'))
        btn_27 = qtw.QPushButton(clicked = lambda: self.buttonselect('27'))
        btn_28 = qtw.QPushButton(clicked = lambda: self.buttonselect('28'))
        btn_29 = qtw.QPushButton(clicked = lambda: self.buttonselect('29'))
        btn_31 = qtw.QPushButton(clicked = lambda: self.buttonselect('31'))
        btn_32 = qtw.QPushButton(clicked = lambda: self.buttonselect('32'))
        btn_33 = qtw.QPushButton(clicked = lambda: self.buttonselect('33'))
        btn_34 = qtw.QPushButton(clicked = lambda: self.buttonselect('34'))
        btn_35 = qtw.QPushButton(clicked = lambda: self.buttonselect('35'))
        btn_36 = qtw.QPushButton(clicked = lambda: self.buttonselect('36'))
        btn_37 = qtw.QPushButton(clicked = lambda: self.buttonselect('37'))
        btn_38 = qtw.QPushButton(clicked = lambda: self.buttonselect('38'))
        btn_39 = qtw.QPushButton(clicked = lambda: self.buttonselect('39'))
        btn_41 = qtw.QPushButton(clicked = lambda: self.buttonselect('41'))
        btn_42 = qtw.QPushButton(clicked = lambda: self.buttonselect('42'))
        btn_43 = qtw.QPushButton(clicked = lambda: self.buttonselect('43'))
        btn_44 = qtw.QPushButton(clicked = lambda: self.buttonselect('44'))
        btn_45 = qtw.QPushButton(clicked = lambda: self.buttonselect('45'))
        btn_46 = qtw.QPushButton(clicked = lambda: self.buttonselect('46'))
        btn_47 = qtw.QPushButton(clicked = lambda: self.buttonselect('47'))
        btn_48 = qtw.QPushButton(clicked = lambda: self.buttonselect('48'))
        btn_49 = qtw.QPushButton(clicked = lambda: self.buttonselect('49'))
        btn_51 = qtw.QPushButton(clicked = lambda: self.buttonselect('51'))
        btn_52 = qtw.QPushButton(clicked = lambda: self.buttonselect('52'))
        btn_53 = qtw.QPushButton(clicked = lambda: self.buttonselect('53'))
        btn_54 = qtw.QPushButton(clicked = lambda: self.buttonselect('54'))
        btn_55 = qtw.QPushButton(clicked = lambda: self.buttonselect('55'))
        btn_56 = qtw.QPushButton(clicked = lambda: self.buttonselect('56'))
        btn_57 = qtw.QPushButton(clicked = lambda: self.buttonselect('57'))
        btn_58 = qtw.QPushButton(clicked = lambda: self.buttonselect('58'))
        btn_59 = qtw.QPushButton(clicked = lambda: self.buttonselect('59'))
        btn_61 = qtw.QPushButton(clicked = lambda: self.buttonselect('61'))
        btn_62 = qtw.QPushButton(clicked = lambda: self.buttonselect('62'))
        btn_63 = qtw.QPushButton(clicked = lambda: self.buttonselect('63'))
        btn_64 = qtw.QPushButton(clicked = lambda: self.buttonselect('64'))
        btn_65 = qtw.QPushButton(clicked = lambda: self.buttonselect('65'))
        btn_66 = qtw.QPushButton(clicked = lambda: self.buttonselect('66'))
        btn_67 = qtw.QPushButton(clicked = lambda: self.buttonselect('67'))
        btn_68 = qtw.QPushButton(clicked = lambda: self.buttonselect('68'))
        btn_69 = qtw.QPushButton(clicked = lambda: self.buttonselect('69'))
        btn_71 = qtw.QPushButton(clicked = lambda: self.buttonselect('71'))
        btn_72 = qtw.QPushButton(clicked = lambda: self.buttonselect('72'))
        btn_73 = qtw.QPushButton(clicked = lambda: self.buttonselect('73'))
        btn_74 = qtw.QPushButton(clicked = lambda: self.buttonselect('74'))
        btn_75 = qtw.QPushButton(clicked = lambda: self.buttonselect('75'))
        btn_76 = qtw.QPushButton(clicked = lambda: self.buttonselect('76'))
        btn_77 = qtw.QPushButton(clicked = lambda: self.buttonselect('77'))
        btn_78 = qtw.QPushButton(clicked = lambda: self.buttonselect('78'))
        btn_79 = qtw.QPushButton(clicked = lambda: self.buttonselect('79'))
        btn_81 = qtw.QPushButton(clicked = lambda: self.buttonselect('81'))
        btn_82 = qtw.QPushButton(clicked = lambda: self.buttonselect('82'))
        btn_83 = qtw.QPushButton(clicked = lambda: self.buttonselect('83'))
        btn_84 = qtw.QPushButton(clicked = lambda: self.buttonselect('84'))
        btn_85 = qtw.QPushButton(clicked = lambda: self.buttonselect('85'))
        btn_86 = qtw.QPushButton(clicked = lambda: self.buttonselect('86'))
        btn_87 = qtw.QPushButton(clicked = lambda: self.buttonselect('87'))
        btn_88 = qtw.QPushButton(clicked = lambda: self.buttonselect('88'))
        btn_89 = qtw.QPushButton(clicked = lambda: self.buttonselect('89'))
        btn_104 = qtw.QPushButton(clicked = lambda: self.buttonselect('104'))
        btn_105 = qtw.QPushButton(clicked = lambda: self.buttonselect('105'))
        btn_106 = qtw.QPushButton(clicked = lambda: self.buttonselect('106'))
        btn_107 = qtw.QPushButton(clicked = lambda: self.buttonselect('107'))
        btn_108 = qtw.QPushButton(clicked = lambda: self.buttonselect('108'))
        btn_109 = qtw.QPushButton(clicked = lambda: self.buttonselect('109'))
        btn_110 = qtw.QPushButton(clicked = lambda: self.buttonselect('110'))
        btn_111 = qtw.QPushButton(clicked = lambda: self.buttonselect('111'))

        container.layout().addWidget(btn_104, 1, 0)
        container.layout().addWidget(btn_105, 1, 1)
        container.layout().addWidget(btn_106, 1, 2)
        container.layout().addWidget(btn_107, 1, 3)
        container.layout().addWidget(btn_108, 1, 4)
        container.layout().addWidget(btn_109, 1, 5)
        container.layout().addWidget(btn_110, 1, 6)
        container.layout().addWidget(btn_111, 1, 7)
        container.layout().addWidget(btn_81, 2, 0)
        container.layout().addWidget(btn_82, 2, 1)
        container.layout().addWidget(btn_83, 2, 2)
        container.layout().addWidget(btn_84, 2, 3)
        container.layout().addWidget(btn_85, 2, 4)
        container.layout().addWidget(btn_86, 2, 5)
        container.layout().addWidget(btn_87, 2, 6)
        container.layout().addWidget(btn_88, 2, 7)
        container.layout().addWidget(btn_89, 2, 8)
        container.layout().addWidget(btn_71, 3, 0)
        container.layout().addWidget(btn_72, 3, 1)
        container.layout().addWidget(btn_73, 3, 2)
        container.layout().addWidget(btn_74, 3, 3)
        container.layout().addWidget(btn_75, 3, 4)
        container.layout().addWidget(btn_76, 3, 5)
        container.layout().addWidget(btn_77, 3, 6)
        container.layout().addWidget(btn_78, 3, 7)
        container.layout().addWidget(btn_79, 3, 8)
        container.layout().addWidget(btn_61, 4, 0)
        container.layout().addWidget(btn_62, 4, 1)
        container.layout().addWidget(btn_63, 4, 2)
        container.layout().addWidget(btn_64, 4, 3)
        container.layout().addWidget(btn_65, 4, 4)
        container.layout().addWidget(btn_66, 4, 5)
        container.layout().addWidget(btn_67, 4, 6)
        container.layout().addWidget(btn_68, 4, 7)
        container.layout().addWidget(btn_69, 4, 8)
        container.layout().addWidget(btn_51, 5, 0)
        container.layout().addWidget(btn_52, 5, 1)
        container.layout().addWidget(btn_53, 5, 2)
        container.layout().addWidget(btn_54, 5, 3)
        container.layout().addWidget(btn_55, 5, 4)
        container.layout().addWidget(btn_56, 5, 5)
        container.layout().addWidget(btn_57, 5, 6)
        container.layout().addWidget(btn_58, 5, 7)
        container.layout().addWidget(btn_59, 5, 8)
        container.layout().addWidget(btn_41, 6, 0)
        container.layout().addWidget(btn_42, 6, 1)
        container.layout().addWidget(btn_43, 6, 2)
        container.layout().addWidget(btn_44, 6, 3)
        container.layout().addWidget(btn_45, 6, 4)
        container.layout().addWidget(btn_46, 6, 5)
        container.layout().addWidget(btn_47, 6, 6)
        container.layout().addWidget(btn_48, 6, 7)
        container.layout().addWidget(btn_49, 6, 8)
        container.layout().addWidget(btn_31, 7, 0)
        container.layout().addWidget(btn_32, 7, 1)
        container.layout().addWidget(btn_33, 7, 2)
        container.layout().addWidget(btn_34, 7, 3)
        container.layout().addWidget(btn_35, 7, 4)
        container.layout().addWidget(btn_36, 7, 5)
        container.layout().addWidget(btn_37, 7, 6)
        container.layout().addWidget(btn_38, 7, 7)
        container.layout().addWidget(btn_39, 7, 8)
        container.layout().addWidget(btn_21, 8, 0)
        container.layout().addWidget(btn_22, 8, 1)
        container.layout().addWidget(btn_23, 8, 2)
        container.layout().addWidget(btn_24, 8, 3)
        container.layout().addWidget(btn_25, 8, 4)
        container.layout().addWidget(btn_26, 8, 5)
        container.layout().addWidget(btn_27, 8, 6)
        container.layout().addWidget(btn_28, 8, 7)
        container.layout().addWidget(btn_29, 8, 8)
        container.layout().addWidget(btn_11, 9, 0)
        container.layout().addWidget(btn_12, 9, 1)
        container.layout().addWidget(btn_13, 9, 2)
        container.layout().addWidget(btn_14, 9, 3)
        container.layout().addWidget(btn_15, 9, 4)
        container.layout().addWidget(btn_16, 9, 5)
        container.layout().addWidget(btn_17, 9, 6)
        container.layout().addWidget(btn_18, 9, 7)
        container.layout().addWidget(btn_19, 9, 8)
        
        self.layout().addWidget(container)

    def buttonselect(self, text):
        print(text)

    def onActivated(self, text):
        container1 = qtw.QWidget()
        container1.setLayout(qtw.QGridLayout())
        if text == "open file":
            openFile = qtw.QPushButton('open file', self)
            container1.layout().addWidget(openFile, 0, 4)
        elif text == "open chrome tab":
            cmdInput = qtw.QLineEdit(self)
            container1.layout().addWidget(cmdInput, 0, 4, 1, 3)
            submit = qtw.QPushButton('submit', self)
            container1.layout().addWidget(submit, 0, 7)
        elif text == "keyboard shortcut":
            cmdInput = qtw.QLineEdit(self)
            container1.layout().addWidget(cmdInput, 0, 4, 1, 3)
            submit = qtw.QPushButton('submit', self)
            container1.layout().addWidget(submit, 0, 7)
        else:
            print("nothing")
        self.layout().addWidget(container1)

    def execute(self):
        self.thread = QThread()
        self.worker = Worker()
        self.worker.moveToThread(self.thread)

        self.thread.started.connect(self.worker.run)
        self.worker.finished.connect(self.thread.quit)
        self.worker.finished.connect(self.worker.deleteLater)
        self.thread.finished.connect(self.thread.deleteLater)

        self.thread.start()

app = qtw.QApplication(sys.argv)
mw = MainWindow()
app.setStyle(qtw.QStyleFactory.create('Fusion'))
app.exec_()