from PyQt5.QtCore import QObject, QThread, pyqtSignal
import PyQt5.QtWidgets as qtw
import PyQt5.QtGui as qtg
import Midi_Input as mi
import subprocess
import sys

#execute Midi_Input.py as script in shell
# def executeMidiInput():
#     subprocess.call(['python', 'Midi_Input.py'])

class Worker(QObject):
    finished = pyqtSignal()

    def run(self):
        # Here we pass the update_progress (uncalled!)
        # function to the long_running_function:
        # executeMidiInput()
        mi.runMidi()
        self.finished.emit()

class MainWindow(qtw.QWidget):
    def __init__(self):
        super().__init__()
        self.setWindowTitle('Launchdeck')
        self.setStyleSheet("background-color: #1f1f1f;")
        # self.setStyleSheet("QPushButton {color: #bababa;}")
        self.setLayout(qtw.QVBoxLayout())
        self.buttongrid()

        self.show()
    def buttongrid(self):
        container = qtw.QWidget()
        container.setLayout(qtw.QGridLayout())
        
        titleLP = qtw.QLabel('Launchdeck')
        comboBox = qtw.QComboBox(self)
        btn_start = qtw.QPushButton('Start', clicked = self.execute)
        btn_11 = qtw.QPushButton('11')
        btn_12 = qtw.QPushButton('12')
        btn_13 = qtw.QPushButton('13')
        btn_14 = qtw.QPushButton('14')
        btn_15 = qtw.QPushButton('15')
        btn_16 = qtw.QPushButton('16')
        btn_17 = qtw.QPushButton('17')
        btn_18 = qtw.QPushButton('18')
        btn_19 = qtw.QPushButton('19')
        btn_21 = qtw.QPushButton('21')
        btn_22 = qtw.QPushButton('22')
        btn_23 = qtw.QPushButton('23')
        btn_24 = qtw.QPushButton('24')
        btn_25 = qtw.QPushButton('25')
        btn_26 = qtw.QPushButton('26')
        btn_27 = qtw.QPushButton('27')
        btn_28 = qtw.QPushButton('28')
        btn_29 = qtw.QPushButton('29')
        btn_31 = qtw.QPushButton('31')
        btn_32 = qtw.QPushButton('32')
        btn_33 = qtw.QPushButton('33')
        btn_34 = qtw.QPushButton('34')
        btn_35 = qtw.QPushButton('35')
        btn_36 = qtw.QPushButton('36')
        btn_37 = qtw.QPushButton('37')
        btn_38 = qtw.QPushButton('38')
        btn_39 = qtw.QPushButton('39')
        btn_41 = qtw.QPushButton('41')
        btn_42 = qtw.QPushButton('42')
        btn_43 = qtw.QPushButton('43')
        btn_44 = qtw.QPushButton('44')
        btn_45 = qtw.QPushButton('45')
        btn_46 = qtw.QPushButton('46')
        btn_47 = qtw.QPushButton('47')
        btn_48 = qtw.QPushButton('48')
        btn_49 = qtw.QPushButton('49')
        btn_51 = qtw.QPushButton('51')
        btn_52 = qtw.QPushButton('52')
        btn_53 = qtw.QPushButton('53')
        btn_54 = qtw.QPushButton('54')
        btn_55 = qtw.QPushButton('55')
        btn_56 = qtw.QPushButton('56')
        btn_57 = qtw.QPushButton('57')
        btn_58 = qtw.QPushButton('58')
        btn_59 = qtw.QPushButton('59')
        btn_61 = qtw.QPushButton('61')
        btn_62 = qtw.QPushButton('62')
        btn_63 = qtw.QPushButton('63')
        btn_64 = qtw.QPushButton('64')
        btn_65 = qtw.QPushButton('65')
        btn_66 = qtw.QPushButton('66')
        btn_67 = qtw.QPushButton('67')
        btn_68 = qtw.QPushButton('68')
        btn_69 = qtw.QPushButton('69')
        btn_71 = qtw.QPushButton('71')
        btn_72 = qtw.QPushButton('72')
        btn_73 = qtw.QPushButton('73')
        btn_74 = qtw.QPushButton('74')
        btn_75 = qtw.QPushButton('75')
        btn_76 = qtw.QPushButton('76')
        btn_77 = qtw.QPushButton('77')
        btn_78 = qtw.QPushButton('78')
        btn_79 = qtw.QPushButton('79')
        btn_81 = qtw.QPushButton('81')
        btn_82 = qtw.QPushButton('82')
        btn_83 = qtw.QPushButton('83')
        btn_84 = qtw.QPushButton('84')
        btn_85 = qtw.QPushButton('85')
        btn_86 = qtw.QPushButton('86')
        btn_87 = qtw.QPushButton('87')
        btn_88 = qtw.QPushButton('88')
        btn_89 = qtw.QPushButton('89')
        btn_104 = qtw.QPushButton('104')
        btn_105 = qtw.QPushButton('105')
        btn_106 = qtw.QPushButton('106')
        btn_107 = qtw.QPushButton('107')
        btn_108 = qtw.QPushButton('108')
        btn_109 = qtw.QPushButton('109')
        btn_110 = qtw.QPushButton('110')
        btn_111 = qtw.QPushButton('111')

        container.layout().addWidget(titleLP, 0, 0)
        container.layout().addWidget(btn_104, 1, 0)
        container.layout().addWidget(btn_105, 1, 1)
        container.layout().addWidget(btn_106, 1, 2)
        container.layout().addWidget(btn_107, 1, 3)
        container.layout().addWidget(btn_108, 1, 4)
        container.layout().addWidget(btn_109, 1, 5)
        container.layout().addWidget(btn_110, 1, 6)
        container.layout().addWidget(btn_111, 1, 7)
        container.layout().addWidget(btn_start, 0, 8)
        container.layout().addWidget(btn_81, 2, 0)
        container.layout().addWidget(btn_82, 2, 1)
        container.layout().addWidget(btn_83, 2, 2)
        container.layout().addWidget(btn_84, 2, 3)
        container.layout().addWidget(btn_85, 2, 4)
        container.layout().addWidget(btn_86, 2, 5)
        container.layout().addWidget(btn_87, 2, 6)
        container.layout().addWidget(btn_88, 2, 7)
        container.layout().addWidget(btn_89, 2, 8)
        container.layout().addWidget(btn_71, 3, 0)
        container.layout().addWidget(btn_72, 3, 1)
        container.layout().addWidget(btn_73, 3, 2)
        container.layout().addWidget(btn_74, 3, 3)
        container.layout().addWidget(btn_75, 3, 4)
        container.layout().addWidget(btn_76, 3, 5)
        container.layout().addWidget(btn_77, 3, 6)
        container.layout().addWidget(btn_78, 3, 7)
        container.layout().addWidget(btn_79, 3, 8)
        container.layout().addWidget(btn_61, 4, 0)
        container.layout().addWidget(btn_62, 4, 1)
        container.layout().addWidget(btn_63, 4, 2)
        container.layout().addWidget(btn_64, 4, 3)
        container.layout().addWidget(btn_65, 4, 4)
        container.layout().addWidget(btn_66, 4, 5)
        container.layout().addWidget(btn_67, 4, 6)
        container.layout().addWidget(btn_68, 4, 7)
        container.layout().addWidget(btn_69, 4, 8)
        container.layout().addWidget(btn_51, 5, 0)
        container.layout().addWidget(btn_52, 5, 1)
        container.layout().addWidget(btn_53, 5, 2)
        container.layout().addWidget(btn_54, 5, 3)
        container.layout().addWidget(btn_55, 5, 4)
        container.layout().addWidget(btn_56, 5, 5)
        container.layout().addWidget(btn_57, 5, 6)
        container.layout().addWidget(btn_58, 5, 7)
        container.layout().addWidget(btn_59, 5, 8)
        container.layout().addWidget(btn_41, 6, 0)
        container.layout().addWidget(btn_42, 6, 1)
        container.layout().addWidget(btn_43, 6, 2)
        container.layout().addWidget(btn_44, 6, 3)
        container.layout().addWidget(btn_45, 6, 4)
        container.layout().addWidget(btn_46, 6, 5)
        container.layout().addWidget(btn_47, 6, 6)
        container.layout().addWidget(btn_48, 6, 7)
        container.layout().addWidget(btn_49, 6, 8)
        container.layout().addWidget(btn_31, 7, 0)
        container.layout().addWidget(btn_32, 7, 1)
        container.layout().addWidget(btn_33, 7, 2)
        container.layout().addWidget(btn_34, 7, 3)
        container.layout().addWidget(btn_35, 7, 4)
        container.layout().addWidget(btn_36, 7, 5)
        container.layout().addWidget(btn_37, 7, 6)
        container.layout().addWidget(btn_38, 7, 7)
        container.layout().addWidget(btn_39, 7, 8)
        container.layout().addWidget(btn_21, 8, 0)
        container.layout().addWidget(btn_22, 8, 1)
        container.layout().addWidget(btn_23, 8, 2)
        container.layout().addWidget(btn_24, 8, 3)
        container.layout().addWidget(btn_25, 8, 4)
        container.layout().addWidget(btn_26, 8, 5)
        container.layout().addWidget(btn_27, 8, 6)
        container.layout().addWidget(btn_28, 8, 7)
        container.layout().addWidget(btn_29, 8, 8)
        container.layout().addWidget(btn_11, 9, 0)
        container.layout().addWidget(btn_12, 9, 1)
        container.layout().addWidget(btn_13, 9, 2)
        container.layout().addWidget(btn_14, 9, 3)
        container.layout().addWidget(btn_15, 9, 4)
        container.layout().addWidget(btn_16, 9, 5)
        container.layout().addWidget(btn_17, 9, 6)
        container.layout().addWidget(btn_18, 9, 7)
        container.layout().addWidget(btn_19, 9, 8)
        
        #combo box start
        comboBox.addItem("select function")
        comboBox.addItem("open file")
        comboBox.addItem("open chrome tab")
        comboBox.addItem("keyboard shortcut")
        container.layout().addWidget(comboBox, 0, 2, 1, 2)

        comboBox.activated[str].connect(self.style_choice)
        self.layout().addWidget(container)

    def style_choice(self, text):
        self.styleChoice.setText(text)
        qtw.QApplication.setStyle(qtw.QStyleFactory.create(text))
        #combo box end

    def execute(self):
        self.thread = QThread()
        self.worker = Worker()
        self.worker.moveToThread(self.thread)

        self.thread.started.connect(self.worker.run)
        self.worker.finished.connect(self.thread.quit)
        self.worker.finished.connect(self.worker.deleteLater)
        self.thread.finished.connect(self.thread.deleteLater)

        self.thread.start()

app = qtw.QApplication(sys.argv)
mw = MainWindow()
app.setStyle(qtw.QStyleFactory.create('Fusion'))
app.exec_()